"""add_multiempresa_support

Revision ID: cb616532fc63
Revises: 3beb9aeebdce
Create Date: 2025-09-21 02:24:34.945323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb616532fc63'
down_revision: Union[str, None] = '3beb9aeebdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=150), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=True),
    sa.Column('next_invoice_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_tax_id'), 'companies', ['tax_id'], unique=True)
    op.add_column('categories', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'companies', ['company_id'], ['id'])
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('tax_id', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.add_column('invoices', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_foreign_key(None, 'invoices', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.add_column('purchases', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('purchases', sa.Column('purchase_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_purchases_purchase_number'), 'purchases', ['purchase_number'], unique=False)
    op.create_foreign_key(None, 'purchases', 'companies', ['company_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('tax_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_company_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.add_column('warehouses', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'warehouses', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_company_admin')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'tax_id')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_purchase_number'), table_name='purchases')
    op.drop_column('purchases', 'purchase_number')
    op.drop_column('purchases', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.drop_column('customers', 'tax_id')
    op.drop_column('customers', 'company_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'company_id')
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
