"""add_warehouse_id_to_inventory_movements

Revision ID: e99c6812febf
Revises: cb616532fc63
Create Date: 2026-01-06 11:35:02.367768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e99c6812febf'
down_revision: Union[str, None] = 'cb616532fc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_inventory_movements_warehouse_id', 'inventory_movements', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inventory_movements_warehouse_id', 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'warehouse_id')
    # ### end Alembic commands ###
